### ISSUE TITLE
[Q] Service Management Query type ?

### ISSUE THREAD

**Issue by VladGhelbere** [bmcsoftware/bmchelix-datasource#8]
Hello, I am rather new to working with BMC in general. So please disregard if this is a weird question. Do you plan on adding Service Management as a Query type for the plugin anywhere in the future ? Or is that not on your roadmap.

**Comment by bfarrell** [comment]
Please see here:
https://docs.bmc.com/docs//bhd/222/service-management-query-1077398377.html

**Comment by VladGhelbere** [comment]
Hi @bfarrell , thanks for your answer ! This is how I suppose you'd do it in a BMC Dashboard, which uses underlying Grafana. I am asking if there is any plans to make this currently available in Grafana through the Grafana plugin. Because using the plugin v3.0 I can currently see only: "Events", "Metric", "CloudSecurity" & "Log" as a selectable Query type. Am I missing something ?

**Comment by bfarrell** [comment]
Ah, got it.  Right now the ITSM query type is not supported in the public version.  We are looking to add this support, likely in a separate public ITSM specific plugin.  However, we don’t have timelines at this point.

**Comment by VladGhelbere** [comment]
Understood. Thanks a lot for the reply !
